// Mocks generated by Mockito 5.4.6 from annotations
// in Dividex/test/auth/presentation/pages/otp_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:Dividex/config/l10n/app_localizations.dart' as _i6;
import 'package:Dividex/features/auth/presentation/bloc/auth_bloc.dart' as _i2;
import 'package:Dividex/features/auth/presentation/bloc/auth_event.dart' as _i4;
import 'package:flutter_bloc/flutter_bloc.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthState_0 extends _i1.SmartFake implements _i2.AuthState {
  _FakeAuthState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthBloc extends _i1.Mock implements _i2.AuthBloc {
  MockAuthBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAuthState_0(this, Invocation.getter(#state)),
          )
          as _i2.AuthState);

  @override
  _i3.Stream<_i2.AuthState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i3.Stream<_i2.AuthState>.empty(),
          )
          as _i3.Stream<_i2.AuthState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i4.AuthEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i4.AuthEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i2.AuthState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i4.AuthEvent>(
    _i5.EventHandler<E, _i2.AuthState>? handler, {
    _i5.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(_i5.Transition<_i4.AuthEvent, _i2.AuthState>? transition) =>
      super.noSuchMethod(
        Invocation.method(#onTransition, [transition]),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void onChange(_i5.Change<_i2.AuthState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AppLocalizations].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLocalizations extends _i1.Mock implements _i6.AppLocalizations {
  MockAppLocalizations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get localeName =>
      (super.noSuchMethod(
            Invocation.getter(#localeName),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#localeName),
            ),
          )
          as String);

  @override
  String get addExpense =>
      (super.noSuchMethod(
            Invocation.getter(#addExpense),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#addExpense),
            ),
          )
          as String);

  @override
  String get addGroup =>
      (super.noSuchMethod(
            Invocation.getter(#addGroup),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#addGroup),
            ),
          )
          as String);

  @override
  String get addEvent =>
      (super.noSuchMethod(
            Invocation.getter(#addEvent),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#addEvent),
            ),
          )
          as String);

  @override
  String get error =>
      (super.noSuchMethod(
            Invocation.getter(#error),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#error),
            ),
          )
          as String);

  @override
  String get success =>
      (super.noSuchMethod(
            Invocation.getter(#success),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#success),
            ),
          )
          as String);

  @override
  String get otpSentSuccess =>
      (super.noSuchMethod(
            Invocation.getter(#otpSentSuccess),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#otpSentSuccess),
            ),
          )
          as String);

  @override
  String get emailInput =>
      (super.noSuchMethod(
            Invocation.getter(#emailInput),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#emailInput),
            ),
          )
          as String);

  @override
  String get emailInputDescription =>
      (super.noSuchMethod(
            Invocation.getter(#emailInputDescription),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#emailInputDescription),
            ),
          )
          as String);

  @override
  String get passwordInputDescription =>
      (super.noSuchMethod(
            Invocation.getter(#passwordInputDescription),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#passwordInputDescription),
            ),
          )
          as String);

  @override
  String get emailLabel =>
      (super.noSuchMethod(
            Invocation.getter(#emailLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#emailLabel),
            ),
          )
          as String);

  @override
  String get passwordLabel =>
      (super.noSuchMethod(
            Invocation.getter(#passwordLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#passwordLabel),
            ),
          )
          as String);

  @override
  String get next =>
      (super.noSuchMethod(
            Invocation.getter(#next),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#next)),
          )
          as String);

  @override
  String get forgotPassword =>
      (super.noSuchMethod(
            Invocation.getter(#forgotPassword),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#forgotPassword),
            ),
          )
          as String);

  @override
  String get login =>
      (super.noSuchMethod(
            Invocation.getter(#login),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#login),
            ),
          )
          as String);

  @override
  String get or =>
      (super.noSuchMethod(
            Invocation.getter(#or),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#or)),
          )
          as String);

  @override
  String get loginWithGoogle =>
      (super.noSuchMethod(
            Invocation.getter(#loginWithGoogle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#loginWithGoogle),
            ),
          )
          as String);

  @override
  String get loginPageToRegister =>
      (super.noSuchMethod(
            Invocation.getter(#loginPageToRegister),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#loginPageToRegister),
            ),
          )
          as String);

  @override
  String get register =>
      (super.noSuchMethod(
            Invocation.getter(#register),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#register),
            ),
          )
          as String);

  @override
  String get otpInputPageTitle =>
      (super.noSuchMethod(
            Invocation.getter(#otpInputPageTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#otpInputPageTitle),
            ),
          )
          as String);

  @override
  String get otpInputPageDescription =>
      (super.noSuchMethod(
            Invocation.getter(#otpInputPageDescription),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#otpInputPageDescription),
            ),
          )
          as String);

  @override
  String get otpInputPageDidntReceiveCode =>
      (super.noSuchMethod(
            Invocation.getter(#otpInputPageDidntReceiveCode),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#otpInputPageDidntReceiveCode),
            ),
          )
          as String);

  @override
  String get otpInputPageResend =>
      (super.noSuchMethod(
            Invocation.getter(#otpInputPageResend),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#otpInputPageResend),
            ),
          )
          as String);

  @override
  String get otpInputError1 =>
      (super.noSuchMethod(
            Invocation.getter(#otpInputError1),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#otpInputError1),
            ),
          )
          as String);

  @override
  String get resetPassPageTitle =>
      (super.noSuchMethod(
            Invocation.getter(#resetPassPageTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#resetPassPageTitle),
            ),
          )
          as String);

  @override
  String get resetPassPageDescription =>
      (super.noSuchMethod(
            Invocation.getter(#resetPassPageDescription),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#resetPassPageDescription),
            ),
          )
          as String);

  @override
  String get resetPassNewPassHint =>
      (super.noSuchMethod(
            Invocation.getter(#resetPassNewPassHint),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#resetPassNewPassHint),
            ),
          )
          as String);

  @override
  String get resetPassConfirmPassHint =>
      (super.noSuchMethod(
            Invocation.getter(#resetPassConfirmPassHint),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#resetPassConfirmPassHint),
            ),
          )
          as String);

  @override
  String get save =>
      (super.noSuchMethod(
            Invocation.getter(#save),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#save)),
          )
          as String);

  @override
  String get resetPassSuccess =>
      (super.noSuchMethod(
            Invocation.getter(#resetPassSuccess),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#resetPassSuccess),
            ),
          )
          as String);

  @override
  String get resetPassError =>
      (super.noSuchMethod(
            Invocation.getter(#resetPassError),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#resetPassError),
            ),
          )
          as String);

  @override
  String get newPasswordLabel =>
      (super.noSuchMethod(
            Invocation.getter(#newPasswordLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#newPasswordLabel),
            ),
          )
          as String);

  @override
  String get confirmPasswordLabel =>
      (super.noSuchMethod(
            Invocation.getter(#confirmPasswordLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#confirmPasswordLabel),
            ),
          )
          as String);

  @override
  String get confirmPasswordInputDescription =>
      (super.noSuchMethod(
            Invocation.getter(#confirmPasswordInputDescription),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#confirmPasswordInputDescription),
            ),
          )
          as String);

  @override
  String get phoneLabel =>
      (super.noSuchMethod(
            Invocation.getter(#phoneLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#phoneLabel),
            ),
          )
          as String);

  @override
  String get nameLabel =>
      (super.noSuchMethod(
            Invocation.getter(#nameLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#nameLabel),
            ),
          )
          as String);

  @override
  String get registerPageToLogin =>
      (super.noSuchMethod(
            Invocation.getter(#registerPageToLogin),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#registerPageToLogin),
            ),
          )
          as String);

  @override
  String get emailAlreadyExists =>
      (super.noSuchMethod(
            Invocation.getter(#emailAlreadyExists),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#emailAlreadyExists),
            ),
          )
          as String);

  @override
  String get phoneNumberAlreadyExists =>
      (super.noSuchMethod(
            Invocation.getter(#phoneNumberAlreadyExists),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#phoneNumberAlreadyExists),
            ),
          )
          as String);

  @override
  String get emailNotFound =>
      (super.noSuchMethod(
            Invocation.getter(#emailNotFound),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#emailNotFound),
            ),
          )
          as String);

  @override
  String get userNotFound =>
      (super.noSuchMethod(
            Invocation.getter(#userNotFound),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#userNotFound),
            ),
          )
          as String);

  @override
  String get noTransaction =>
      (super.noSuchMethod(
            Invocation.getter(#noTransaction),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#noTransaction),
            ),
          )
          as String);

  @override
  String get addFirstTransaction =>
      (super.noSuchMethod(
            Invocation.getter(#addFirstTransaction),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#addFirstTransaction),
            ),
          )
          as String);

  @override
  String get expenseNameLabel =>
      (super.noSuchMethod(
            Invocation.getter(#expenseNameLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#expenseNameLabel),
            ),
          )
          as String);

  @override
  String get expenseNameHint =>
      (super.noSuchMethod(
            Invocation.getter(#expenseNameHint),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#expenseNameHint),
            ),
          )
          as String);

  @override
  String get expenseAmountLabel =>
      (super.noSuchMethod(
            Invocation.getter(#expenseAmountLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#expenseAmountLabel),
            ),
          )
          as String);

  @override
  String get expenseAmountHint =>
      (super.noSuchMethod(
            Invocation.getter(#expenseAmountHint),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#expenseAmountHint),
            ),
          )
          as String);

  @override
  String get expenseUnitLabel =>
      (super.noSuchMethod(
            Invocation.getter(#expenseUnitLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#expenseUnitLabel),
            ),
          )
          as String);

  @override
  String get expenseCategoryLabel =>
      (super.noSuchMethod(
            Invocation.getter(#expenseCategoryLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#expenseCategoryLabel),
            ),
          )
          as String);

  @override
  String get expenseEventLabel =>
      (super.noSuchMethod(
            Invocation.getter(#expenseEventLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#expenseEventLabel),
            ),
          )
          as String);

  @override
  String get expensePayerLabel =>
      (super.noSuchMethod(
            Invocation.getter(#expensePayerLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#expensePayerLabel),
            ),
          )
          as String);

  @override
  String get expenseSplitEquallyLabel =>
      (super.noSuchMethod(
            Invocation.getter(#expenseSplitEquallyLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#expenseSplitEquallyLabel),
            ),
          )
          as String);

  @override
  String get expenseSplitCustomLabel =>
      (super.noSuchMethod(
            Invocation.getter(#expenseSplitCustomLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#expenseSplitCustomLabel),
            ),
          )
          as String);

  @override
  String get addConfigLabel =>
      (super.noSuchMethod(
            Invocation.getter(#addConfigLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#addConfigLabel),
            ),
          )
          as String);

  @override
  String get expenseNoteLabel =>
      (super.noSuchMethod(
            Invocation.getter(#expenseNoteLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#expenseNoteLabel),
            ),
          )
          as String);

  @override
  String get expenseDateLabel =>
      (super.noSuchMethod(
            Invocation.getter(#expenseDateLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#expenseDateLabel),
            ),
          )
          as String);

  @override
  String get expenseReminderLabel =>
      (super.noSuchMethod(
            Invocation.getter(#expenseReminderLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#expenseReminderLabel),
            ),
          )
          as String);

  @override
  String get addExpenseImageLabel =>
      (super.noSuchMethod(
            Invocation.getter(#addExpenseImageLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#addExpenseImageLabel),
            ),
          )
          as String);

  @override
  String get add =>
      (super.noSuchMethod(
            Invocation.getter(#add),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#add)),
          )
          as String);

  @override
  String get eventNameLabel =>
      (super.noSuchMethod(
            Invocation.getter(#eventNameLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#eventNameLabel),
            ),
          )
          as String);

  @override
  String get eventNameHint =>
      (super.noSuchMethod(
            Invocation.getter(#eventNameHint),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#eventNameHint),
            ),
          )
          as String);

  @override
  String get eventGroupLabel =>
      (super.noSuchMethod(
            Invocation.getter(#eventGroupLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#eventGroupLabel),
            ),
          )
          as String);

  @override
  String get eventStartDateLabel =>
      (super.noSuchMethod(
            Invocation.getter(#eventStartDateLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#eventStartDateLabel),
            ),
          )
          as String);

  @override
  String get eventEndDateLabel =>
      (super.noSuchMethod(
            Invocation.getter(#eventEndDateLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#eventEndDateLabel),
            ),
          )
          as String);

  @override
  String get eventMembers =>
      (super.noSuchMethod(
            Invocation.getter(#eventMembers),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#eventMembers),
            ),
          )
          as String);

  @override
  String get eventDescriptionLabel =>
      (super.noSuchMethod(
            Invocation.getter(#eventDescriptionLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#eventDescriptionLabel),
            ),
          )
          as String);

  @override
  String get eventDescriptionHint =>
      (super.noSuchMethod(
            Invocation.getter(#eventDescriptionHint),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#eventDescriptionHint),
            ),
          )
          as String);

  @override
  String get addGroupImageLabel =>
      (super.noSuchMethod(
            Invocation.getter(#addGroupImageLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#addGroupImageLabel),
            ),
          )
          as String);

  @override
  String get groupNameLabel =>
      (super.noSuchMethod(
            Invocation.getter(#groupNameLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#groupNameLabel),
            ),
          )
          as String);

  @override
  String get groupNameHint =>
      (super.noSuchMethod(
            Invocation.getter(#groupNameHint),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#groupNameHint),
            ),
          )
          as String);

  @override
  String get appTitleHome =>
      (super.noSuchMethod(
            Invocation.getter(#appTitleHome),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#appTitleHome),
            ),
          )
          as String);

  @override
  String get searchTab =>
      (super.noSuchMethod(
            Invocation.getter(#searchTab),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#searchTab),
            ),
          )
          as String);

  @override
  String get appTitleCommunity =>
      (super.noSuchMethod(
            Invocation.getter(#appTitleCommunity),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#appTitleCommunity),
            ),
          )
          as String);

  @override
  String get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#settings),
            ),
          )
          as String);

  @override
  String get qrCode =>
      (super.noSuchMethod(
            Invocation.getter(#qrCode),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#qrCode),
            ),
          )
          as String);

  @override
  String get profileSetting =>
      (super.noSuchMethod(
            Invocation.getter(#profileSetting),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#profileSetting),
            ),
          )
          as String);

  @override
  String get settingLanguage =>
      (super.noSuchMethod(
            Invocation.getter(#settingLanguage),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#settingLanguage),
            ),
          )
          as String);

  @override
  String get settingChooseLanguage =>
      (super.noSuchMethod(
            Invocation.getter(#settingChooseLanguage),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#settingChooseLanguage),
            ),
          )
          as String);

  @override
  String get settingChooseEng =>
      (super.noSuchMethod(
            Invocation.getter(#settingChooseEng),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#settingChooseEng),
            ),
          )
          as String);

  @override
  String get settingChooseVie =>
      (super.noSuchMethod(
            Invocation.getter(#settingChooseVie),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#settingChooseVie),
            ),
          )
          as String);

  @override
  String get settingTheme =>
      (super.noSuchMethod(
            Invocation.getter(#settingTheme),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#settingTheme),
            ),
          )
          as String);

  @override
  String get settingChooseTheme =>
      (super.noSuchMethod(
            Invocation.getter(#settingChooseTheme),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#settingChooseTheme),
            ),
          )
          as String);

  @override
  String get settingChooseDark =>
      (super.noSuchMethod(
            Invocation.getter(#settingChooseDark),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#settingChooseDark),
            ),
          )
          as String);

  @override
  String get settingChooseLight =>
      (super.noSuchMethod(
            Invocation.getter(#settingChooseLight),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#settingChooseLight),
            ),
          )
          as String);

  @override
  String get settingTerm =>
      (super.noSuchMethod(
            Invocation.getter(#settingTerm),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#settingTerm),
            ),
          )
          as String);

  @override
  String get settingSecurity =>
      (super.noSuchMethod(
            Invocation.getter(#settingSecurity),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#settingSecurity),
            ),
          )
          as String);

  @override
  String get securitySettings =>
      (super.noSuchMethod(
            Invocation.getter(#securitySettings),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#securitySettings),
            ),
          )
          as String);

  @override
  String get settingChangePass =>
      (super.noSuchMethod(
            Invocation.getter(#settingChangePass),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#settingChangePass),
            ),
          )
          as String);

  @override
  String get signOut =>
      (super.noSuchMethod(
            Invocation.getter(#signOut),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#signOut),
            ),
          )
          as String);

  @override
  String get accept =>
      (super.noSuchMethod(
            Invocation.getter(#accept),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#accept),
            ),
          )
          as String);

  @override
  String get decline =>
      (super.noSuchMethod(
            Invocation.getter(#decline),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#decline),
            ),
          )
          as String);

  @override
  String get week =>
      (super.noSuchMethod(
            Invocation.getter(#week),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#week)),
          )
          as String);

  @override
  String get day =>
      (super.noSuchMethod(
            Invocation.getter(#day),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#day)),
          )
          as String);

  @override
  String get hour =>
      (super.noSuchMethod(
            Invocation.getter(#hour),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#hour)),
          )
          as String);

  @override
  String get minute =>
      (super.noSuchMethod(
            Invocation.getter(#minute),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#minute),
            ),
          )
          as String);

  @override
  String get justNow =>
      (super.noSuchMethod(
            Invocation.getter(#justNow),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#justNow),
            ),
          )
          as String);

  @override
  String get ago =>
      (super.noSuchMethod(
            Invocation.getter(#ago),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#ago)),
          )
          as String);

  @override
  String get emailInputError1 =>
      (super.noSuchMethod(
            Invocation.getter(#emailInputError1),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#emailInputError1),
            ),
          )
          as String);

  @override
  String get emailInputError2 =>
      (super.noSuchMethod(
            Invocation.getter(#emailInputError2),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#emailInputError2),
            ),
          )
          as String);

  @override
  String get passInputError1 =>
      (super.noSuchMethod(
            Invocation.getter(#passInputError1),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#passInputError1),
            ),
          )
          as String);

  @override
  String get passInputError2 =>
      (super.noSuchMethod(
            Invocation.getter(#passInputError2),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#passInputError2),
            ),
          )
          as String);

  @override
  String get passInputError3 =>
      (super.noSuchMethod(
            Invocation.getter(#passInputError3),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#passInputError3),
            ),
          )
          as String);

  @override
  String get passInputError4 =>
      (super.noSuchMethod(
            Invocation.getter(#passInputError4),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#passInputError4),
            ),
          )
          as String);

  @override
  String get phoneInputError1 =>
      (super.noSuchMethod(
            Invocation.getter(#phoneInputError1),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#phoneInputError1),
            ),
          )
          as String);

  @override
  String get phoneInputError2 =>
      (super.noSuchMethod(
            Invocation.getter(#phoneInputError2),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#phoneInputError2),
            ),
          )
          as String);

  @override
  String get nameInputError1 =>
      (super.noSuchMethod(
            Invocation.getter(#nameInputError1),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#nameInputError1),
            ),
          )
          as String);

  @override
  String get nameInputError2 =>
      (super.noSuchMethod(
            Invocation.getter(#nameInputError2),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#nameInputError2),
            ),
          )
          as String);

  @override
  String get amountInputError1 =>
      (super.noSuchMethod(
            Invocation.getter(#amountInputError1),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#amountInputError1),
            ),
          )
          as String);

  @override
  String get amountInputError2 =>
      (super.noSuchMethod(
            Invocation.getter(#amountInputError2),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#amountInputError2),
            ),
          )
          as String);

  @override
  String get amountInputError3 =>
      (super.noSuchMethod(
            Invocation.getter(#amountInputError3),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#amountInputError3),
            ),
          )
          as String);

  @override
  String get eventStartError1 =>
      (super.noSuchMethod(
            Invocation.getter(#eventStartError1),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#eventStartError1),
            ),
          )
          as String);

  @override
  String get eventEndError1 =>
      (super.noSuchMethod(
            Invocation.getter(#eventEndError1),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#eventEndError1),
            ),
          )
          as String);

  @override
  String get eventStartError2 =>
      (super.noSuchMethod(
            Invocation.getter(#eventStartError2),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#eventStartError2),
            ),
          )
          as String);

  @override
  String get eventEndError2 =>
      (super.noSuchMethod(
            Invocation.getter(#eventEndError2),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#eventEndError2),
            ),
          )
          as String);

  @override
  String get eventStartAfterEndError =>
      (super.noSuchMethod(
            Invocation.getter(#eventStartAfterEndError),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#eventStartAfterEndError),
            ),
          )
          as String);

  @override
  String get eventEndBeforeStartError =>
      (super.noSuchMethod(
            Invocation.getter(#eventEndBeforeStartError),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#eventEndBeforeStartError),
            ),
          )
          as String);

  @override
  String get less =>
      (super.noSuchMethod(
            Invocation.getter(#less),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#less)),
          )
          as String);

  @override
  String get more =>
      (super.noSuchMethod(
            Invocation.getter(#more),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#more)),
          )
          as String);

  @override
  String get imagePicker1 =>
      (super.noSuchMethod(
            Invocation.getter(#imagePicker1),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#imagePicker1),
            ),
          )
          as String);

  @override
  String get imagePicker2 =>
      (super.noSuchMethod(
            Invocation.getter(#imagePicker2),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#imagePicker2),
            ),
          )
          as String);

  @override
  String get imagePickerError1 =>
      (super.noSuchMethod(
            Invocation.getter(#imagePickerError1),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#imagePickerError1),
            ),
          )
          as String);

  @override
  String get cropImage =>
      (super.noSuchMethod(
            Invocation.getter(#cropImage),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#cropImage),
            ),
          )
          as String);

  @override
  String get sumary =>
      (super.noSuchMethod(
            Invocation.getter(#sumary),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#sumary),
            ),
          )
          as String);

  @override
  String get recentTransaction =>
      (super.noSuchMethod(
            Invocation.getter(#recentTransaction),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#recentTransaction),
            ),
          )
          as String);

  @override
  String get youOwn =>
      (super.noSuchMethod(
            Invocation.getter(#youOwn),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#youOwn),
            ),
          )
          as String);

  @override
  String get ownYou =>
      (super.noSuchMethod(
            Invocation.getter(#ownYou),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#ownYou),
            ),
          )
          as String);

  @override
  String get group =>
      (super.noSuchMethod(
            Invocation.getter(#group),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#group),
            ),
          )
          as String);

  @override
  String get friend =>
      (super.noSuchMethod(
            Invocation.getter(#friend),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#friend),
            ),
          )
          as String);

  @override
  String get remind =>
      (super.noSuchMethod(
            Invocation.getter(#remind),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#remind),
            ),
          )
          as String);

  @override
  String get pay =>
      (super.noSuchMethod(
            Invocation.getter(#pay),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#pay)),
          )
          as String);

  @override
  String get analytics =>
      (super.noSuchMethod(
            Invocation.getter(#analytics),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#analytics),
            ),
          )
          as String);

  @override
  String get noFriends =>
      (super.noSuchMethod(
            Invocation.getter(#noFriends),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#noFriends),
            ),
          )
          as String);

  @override
  String get addFirstFriend =>
      (super.noSuchMethod(
            Invocation.getter(#addFirstFriend),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#addFirstFriend),
            ),
          )
          as String);

  @override
  String get addFriend =>
      (super.noSuchMethod(
            Invocation.getter(#addFriend),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#addFriend),
            ),
          )
          as String);

  @override
  String get sendFriendRequestSuccess =>
      (super.noSuchMethod(
            Invocation.getter(#sendFriendRequestSuccess),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#sendFriendRequestSuccess),
            ),
          )
          as String);

  @override
  String get addFriendMessageHint =>
      (super.noSuchMethod(
            Invocation.getter(#addFriendMessageHint),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#addFriendMessageHint),
            ),
          )
          as String);

  @override
  String get cancel =>
      (super.noSuchMethod(
            Invocation.getter(#cancel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#cancel),
            ),
          )
          as String);

  @override
  String get tryDifferentKeyword =>
      (super.noSuchMethod(
            Invocation.getter(#tryDifferentKeyword),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#tryDifferentKeyword),
            ),
          )
          as String);

  @override
  String get noSearchResults =>
      (super.noSuchMethod(
            Invocation.getter(#noSearchResults),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#noSearchResults),
            ),
          )
          as String);

  @override
  String get result =>
      (super.noSuchMethod(
            Invocation.getter(#result),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#result),
            ),
          )
          as String);

  @override
  String get addFriendMessage =>
      (super.noSuchMethod(
            Invocation.getter(#addFriendMessage),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#addFriendMessage),
            ),
          )
          as String);

  @override
  String get received =>
      (super.noSuchMethod(
            Invocation.getter(#received),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#received),
            ),
          )
          as String);

  @override
  String get sent =>
      (super.noSuchMethod(
            Invocation.getter(#sent),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#sent)),
          )
          as String);

  @override
  String get food =>
      (super.noSuchMethod(
            Invocation.getter(#food),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#food)),
          )
          as String);

  @override
  String get transportation =>
      (super.noSuchMethod(
            Invocation.getter(#transportation),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#transportation),
            ),
          )
          as String);

  @override
  String get utilities =>
      (super.noSuchMethod(
            Invocation.getter(#utilities),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#utilities),
            ),
          )
          as String);

  @override
  String get entertainment =>
      (super.noSuchMethod(
            Invocation.getter(#entertainment),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#entertainment),
            ),
          )
          as String);

  @override
  String get housing =>
      (super.noSuchMethod(
            Invocation.getter(#housing),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#housing),
            ),
          )
          as String);

  @override
  String get healthcare =>
      (super.noSuchMethod(
            Invocation.getter(#healthcare),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#healthcare),
            ),
          )
          as String);

  @override
  String get shopping =>
      (super.noSuchMethod(
            Invocation.getter(#shopping),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#shopping),
            ),
          )
          as String);

  @override
  String get education =>
      (super.noSuchMethod(
            Invocation.getter(#education),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#education),
            ),
          )
          as String);

  @override
  String get savings =>
      (super.noSuchMethod(
            Invocation.getter(#savings),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#savings),
            ),
          )
          as String);

  @override
  String get miscellaneous =>
      (super.noSuchMethod(
            Invocation.getter(#miscellaneous),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#miscellaneous),
            ),
          )
          as String);

  @override
  String get termsOfServiceTitle =>
      (super.noSuchMethod(
            Invocation.getter(#termsOfServiceTitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#termsOfServiceTitle),
            ),
          )
          as String);

  @override
  String get dIVIDEXApp =>
      (super.noSuchMethod(
            Invocation.getter(#dIVIDEXApp),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#dIVIDEXApp),
            ),
          )
          as String);

  @override
  String get acceptanceOfTerms =>
      (super.noSuchMethod(
            Invocation.getter(#acceptanceOfTerms),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#acceptanceOfTerms),
            ),
          )
          as String);

  @override
  String get welcomeMessage =>
      (super.noSuchMethod(
            Invocation.getter(#welcomeMessage),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#welcomeMessage),
            ),
          )
          as String);

  @override
  String get agreementText =>
      (super.noSuchMethod(
            Invocation.getter(#agreementText),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#agreementText),
            ),
          )
          as String);

  @override
  String get disagreementText =>
      (super.noSuchMethod(
            Invocation.getter(#disagreementText),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#disagreementText),
            ),
          )
          as String);

  @override
  String get serviceDescription =>
      (super.noSuchMethod(
            Invocation.getter(#serviceDescription),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#serviceDescription),
            ),
          )
          as String);

  @override
  String get dIVIDEXDescription =>
      (super.noSuchMethod(
            Invocation.getter(#dIVIDEXDescription),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#dIVIDEXDescription),
            ),
          )
          as String);

  @override
  String get createGroups =>
      (super.noSuchMethod(
            Invocation.getter(#createGroups),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#createGroups),
            ),
          )
          as String);

  @override
  String get trackExpenses =>
      (super.noSuchMethod(
            Invocation.getter(#trackExpenses),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#trackExpenses),
            ),
          )
          as String);

  @override
  String get splitPayments =>
      (super.noSuchMethod(
            Invocation.getter(#splitPayments),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#splitPayments),
            ),
          )
          as String);

  @override
  String get sendReminders =>
      (super.noSuchMethod(
            Invocation.getter(#sendReminders),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#sendReminders),
            ),
          )
          as String);

  @override
  String get generateReports =>
      (super.noSuchMethod(
            Invocation.getter(#generateReports),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#generateReports),
            ),
          )
          as String);

  @override
  String get socialInteractions =>
      (super.noSuchMethod(
            Invocation.getter(#socialInteractions),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#socialInteractions),
            ),
          )
          as String);

  @override
  String get receiveNotifications =>
      (super.noSuchMethod(
            Invocation.getter(#receiveNotifications),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#receiveNotifications),
            ),
          )
          as String);

  @override
  String get accountRegistrationSecurity =>
      (super.noSuchMethod(
            Invocation.getter(#accountRegistrationSecurity),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#accountRegistrationSecurity),
            ),
          )
          as String);

  @override
  String get registrationRequirements =>
      (super.noSuchMethod(
            Invocation.getter(#registrationRequirements),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#registrationRequirements),
            ),
          )
          as String);

  @override
  String get ageRequirement =>
      (super.noSuchMethod(
            Invocation.getter(#ageRequirement),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#ageRequirement),
            ),
          )
          as String);

  @override
  String get accurateInfo =>
      (super.noSuchMethod(
            Invocation.getter(#accurateInfo),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#accurateInfo),
            ),
          )
          as String);

  @override
  String get oneUniqueAccount =>
      (super.noSuchMethod(
            Invocation.getter(#oneUniqueAccount),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#oneUniqueAccount),
            ),
          )
          as String);

  @override
  String get emailVerification =>
      (super.noSuchMethod(
            Invocation.getter(#emailVerification),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#emailVerification),
            ),
          )
          as String);

  @override
  String get accountSecurity =>
      (super.noSuchMethod(
            Invocation.getter(#accountSecurity),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#accountSecurity),
            ),
          )
          as String);

  @override
  String get passwordProtection =>
      (super.noSuchMethod(
            Invocation.getter(#passwordProtection),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#passwordProtection),
            ),
          )
          as String);

  @override
  String get unauthorizedUse =>
      (super.noSuchMethod(
            Invocation.getter(#unauthorizedUse),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#unauthorizedUse),
            ),
          )
          as String);

  @override
  String get noSharingResponsibility =>
      (super.noSuchMethod(
            Invocation.getter(#noSharingResponsibility),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#noSharingResponsibility),
            ),
          )
          as String);

  @override
  String get useOfService =>
      (super.noSuchMethod(
            Invocation.getter(#useOfService),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#useOfService),
            ),
          )
          as String);

  @override
  String get grantedRights =>
      (super.noSuchMethod(
            Invocation.getter(#grantedRights),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#grantedRights),
            ),
          )
          as String);

  @override
  String get limitedRight =>
      (super.noSuchMethod(
            Invocation.getter(#limitedRight),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#limitedRight),
            ),
          )
          as String);

  @override
  String get accessUsePersonal =>
      (super.noSuchMethod(
            Invocation.getter(#accessUsePersonal),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#accessUsePersonal),
            ),
          )
          as String);

  @override
  String get manageShareExpenses =>
      (super.noSuchMethod(
            Invocation.getter(#manageShareExpenses),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#manageShareExpenses),
            ),
          )
          as String);

  @override
  String get usageRestrictions =>
      (super.noSuchMethod(
            Invocation.getter(#usageRestrictions),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#usageRestrictions),
            ),
          )
          as String);

  @override
  String get mayNot =>
      (super.noSuchMethod(
            Invocation.getter(#mayNot),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#mayNot),
            ),
          )
          as String);

  @override
  String get illegalPurposes =>
      (super.noSuchMethod(
            Invocation.getter(#illegalPurposes),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#illegalPurposes),
            ),
          )
          as String);

  @override
  String get fakeAccounts =>
      (super.noSuchMethod(
            Invocation.getter(#fakeAccounts),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#fakeAccounts),
            ),
          )
          as String);

  @override
  String get spamHarass =>
      (super.noSuchMethod(
            Invocation.getter(#spamHarass),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#spamHarass),
            ),
          )
          as String);

  @override
  String get manipulateData =>
      (super.noSuchMethod(
            Invocation.getter(#manipulateData),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#manipulateData),
            ),
          )
          as String);

  @override
  String get botsScripts =>
      (super.noSuchMethod(
            Invocation.getter(#botsScripts),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#botsScripts),
            ),
          )
          as String);

  @override
  String get hackSabotage =>
      (super.noSuchMethod(
            Invocation.getter(#hackSabotage),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#hackSabotage),
            ),
          )
          as String);

  @override
  String get userContent =>
      (super.noSuchMethod(
            Invocation.getter(#userContent),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#userContent),
            ),
          )
          as String);

  @override
  String get contentOwnership =>
      (super.noSuchMethod(
            Invocation.getter(#contentOwnership),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#contentOwnership),
            ),
          )
          as String);

  @override
  String get retainOwnership =>
      (super.noSuchMethod(
            Invocation.getter(#retainOwnership),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#retainOwnership),
            ),
          )
          as String);

  @override
  String get dIVIDEXContentRights =>
      (super.noSuchMethod(
            Invocation.getter(#dIVIDEXContentRights),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#dIVIDEXContentRights),
            ),
          )
          as String);

  @override
  String get contentStandards =>
      (super.noSuchMethod(
            Invocation.getter(#contentStandards),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#contentStandards),
            ),
          )
          as String);

  @override
  String get mustNot =>
      (super.noSuchMethod(
            Invocation.getter(#mustNot),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#mustNot),
            ),
          )
          as String);

  @override
  String get falseInfo =>
      (super.noSuchMethod(
            Invocation.getter(#falseInfo),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#falseInfo),
            ),
          )
          as String);

  @override
  String get violatePrivacy =>
      (super.noSuchMethod(
            Invocation.getter(#violatePrivacy),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#violatePrivacy),
            ),
          )
          as String);

  @override
  String get offensiveContent =>
      (super.noSuchMethod(
            Invocation.getter(#offensiveContent),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#offensiveContent),
            ),
          )
          as String);

  @override
  String get unauthorizedAdvertising =>
      (super.noSuchMethod(
            Invocation.getter(#unauthorizedAdvertising),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#unauthorizedAdvertising),
            ),
          )
          as String);

  @override
  String get sharePersonalWithoutConsent =>
      (super.noSuchMethod(
            Invocation.getter(#sharePersonalWithoutConsent),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#sharePersonalWithoutConsent),
            ),
          )
          as String);

  @override
  String get moderationRights =>
      (super.noSuchMethod(
            Invocation.getter(#moderationRights),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#moderationRights),
            ),
          )
          as String);

  @override
  String get reviewRemoveContent =>
      (super.noSuchMethod(
            Invocation.getter(#reviewRemoveContent),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#reviewRemoveContent),
            ),
          )
          as String);

  @override
  String get moderationDecisionsFinal =>
      (super.noSuchMethod(
            Invocation.getter(#moderationDecisionsFinal),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#moderationDecisionsFinal),
            ),
          )
          as String);

  @override
  String get privacyDataProtection =>
      (super.noSuchMethod(
            Invocation.getter(#privacyDataProtection),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#privacyDataProtection),
            ),
          )
          as String);

  @override
  String get informationCollection =>
      (super.noSuchMethod(
            Invocation.getter(#informationCollection),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#informationCollection),
            ),
          )
          as String);

  @override
  String get collectProcessInfo =>
      (super.noSuchMethod(
            Invocation.getter(#collectProcessInfo),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#collectProcessInfo),
            ),
          )
          as String);

  @override
  String get profileInfo =>
      (super.noSuchMethod(
            Invocation.getter(#profileInfo),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#profileInfo),
            ),
          )
          as String);

  @override
  String get expenseData =>
      (super.noSuchMethod(
            Invocation.getter(#expenseData),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#expenseData),
            ),
          )
          as String);

  @override
  String get appUsageInfo =>
      (super.noSuchMethod(
            Invocation.getter(#appUsageInfo),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#appUsageInfo),
            ),
          )
          as String);

  @override
  String get informationSharing =>
      (super.noSuchMethod(
            Invocation.getter(#informationSharing),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#informationSharing),
            ),
          )
          as String);

  @override
  String get infoDisplayedPublicly =>
      (super.noSuchMethod(
            Invocation.getter(#infoDisplayedPublicly),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#infoDisplayedPublicly),
            ),
          )
          as String);

  @override
  String get noSellToThirdParties =>
      (super.noSuchMethod(
            Invocation.getter(#noSellToThirdParties),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#noSellToThirdParties),
            ),
          )
          as String);

  @override
  String get sharedWithPartners =>
      (super.noSuchMethod(
            Invocation.getter(#sharedWithPartners),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#sharedWithPartners),
            ),
          )
          as String);

  @override
  String get freePaidFeatures =>
      (super.noSuchMethod(
            Invocation.getter(#freePaidFeatures),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#freePaidFeatures),
            ),
          )
          as String);

  @override
  String get freeFeatures =>
      (super.noSuchMethod(
            Invocation.getter(#freeFeatures),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#freeFeatures),
            ),
          )
          as String);

  @override
  String get basicFeaturesFree =>
      (super.noSuchMethod(
            Invocation.getter(#basicFeaturesFree),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#basicFeaturesFree),
            ),
          )
          as String);

  @override
  String get createGroupsExpenses =>
      (super.noSuchMethod(
            Invocation.getter(#createGroupsExpenses),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#createGroupsExpenses),
            ),
          )
          as String);

  @override
  String get basicSplitPayments =>
      (super.noSuchMethod(
            Invocation.getter(#basicSplitPayments),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#basicSplitPayments),
            ),
          )
          as String);

  @override
  String get basicReports =>
      (super.noSuchMethod(
            Invocation.getter(#basicReports),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#basicReports),
            ),
          )
          as String);

  @override
  String get paidFeatures =>
      (super.noSuchMethod(
            Invocation.getter(#paidFeatures),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#paidFeatures),
            ),
          )
          as String);

  @override
  String get premiumFeaturesPayment =>
      (super.noSuchMethod(
            Invocation.getter(#premiumFeaturesPayment),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#premiumFeaturesPayment),
            ),
          )
          as String);

  @override
  String get transactionsNotified =>
      (super.noSuchMethod(
            Invocation.getter(#transactionsNotified),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#transactionsNotified),
            ),
          )
          as String);

  @override
  String get refundPolicyPublished =>
      (super.noSuchMethod(
            Invocation.getter(#refundPolicyPublished),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#refundPolicyPublished),
            ),
          )
          as String);

  @override
  String get intellectualProperty =>
      (super.noSuchMethod(
            Invocation.getter(#intellectualProperty),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#intellectualProperty),
            ),
          )
          as String);

  @override
  String get dIVIDEXsRights =>
      (super.noSuchMethod(
            Invocation.getter(#dIVIDEXsRights),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#dIVIDEXsRights),
            ),
          )
          as String);

  @override
  String get appInterfaceLogoOwned =>
      (super.noSuchMethod(
            Invocation.getter(#appInterfaceLogoOwned),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#appInterfaceLogoOwned),
            ),
          )
          as String);

  @override
  String get copyingProhibited =>
      (super.noSuchMethod(
            Invocation.getter(#copyingProhibited),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#copyingProhibited),
            ),
          )
          as String);

  @override
  String get respectingCopyright =>
      (super.noSuchMethod(
            Invocation.getter(#respectingCopyright),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#respectingCopyright),
            ),
          )
          as String);

  @override
  String get respectOthersRights =>
      (super.noSuchMethod(
            Invocation.getter(#respectOthersRights),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#respectOthersRights),
            ),
          )
          as String);

  @override
  String get handleInfringement =>
      (super.noSuchMethod(
            Invocation.getter(#handleInfringement),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#handleInfringement),
            ),
          )
          as String);

  @override
  String get serviceTermination =>
      (super.noSuchMethod(
            Invocation.getter(#serviceTermination),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#serviceTermination),
            ),
          )
          as String);

  @override
  String get terminationByUser =>
      (super.noSuchMethod(
            Invocation.getter(#terminationByUser),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#terminationByUser),
            ),
          )
          as String);

  @override
  String get deleteAccount =>
      (super.noSuchMethod(
            Invocation.getter(#deleteAccount),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#deleteAccount),
            ),
          )
          as String);

  @override
  String get infoRetainedLaw =>
      (super.noSuchMethod(
            Invocation.getter(#infoRetainedLaw),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#infoRetainedLaw),
            ),
          )
          as String);

  @override
  String get terminationByDIVIDEX =>
      (super.noSuchMethod(
            Invocation.getter(#terminationByDIVIDEX),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#terminationByDIVIDEX),
            ),
          )
          as String);

  @override
  String get suspendTerminateAccounts =>
      (super.noSuchMethod(
            Invocation.getter(#suspendTerminateAccounts),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#suspendTerminateAccounts),
            ),
          )
          as String);

  @override
  String get violatingTerms =>
      (super.noSuchMethod(
            Invocation.getter(#violatingTerms),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#violatingTerms),
            ),
          )
          as String);

  @override
  String get illegalHarmfulActivities =>
      (super.noSuchMethod(
            Invocation.getter(#illegalHarmfulActivities),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#illegalHarmfulActivities),
            ),
          )
          as String);

  @override
  String get lawEnforcementRequests =>
      (super.noSuchMethod(
            Invocation.getter(#lawEnforcementRequests),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#lawEnforcementRequests),
            ),
          )
          as String);

  @override
  String get discontinuingService =>
      (super.noSuchMethod(
            Invocation.getter(#discontinuingService),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#discontinuingService),
            ),
          )
          as String);

  @override
  String get disclaimer =>
      (super.noSuchMethod(
            Invocation.getter(#disclaimer),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#disclaimer),
            ),
          )
          as String);

  @override
  String get asIsService =>
      (super.noSuchMethod(
            Invocation.getter(#asIsService),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#asIsService),
            ),
          )
          as String);

  @override
  String get serviceProvidedAsIs =>
      (super.noSuchMethod(
            Invocation.getter(#serviceProvidedAsIs),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#serviceProvidedAsIs),
            ),
          )
          as String);

  @override
  String get noGuaranteeOperation =>
      (super.noSuchMethod(
            Invocation.getter(#noGuaranteeOperation),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#noGuaranteeOperation),
            ),
          )
          as String);

  @override
  String get limitationOfLiability =>
      (super.noSuchMethod(
            Invocation.getter(#limitationOfLiability),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#limitationOfLiability),
            ),
          )
          as String);

  @override
  String get noResponsibilityUserContent =>
      (super.noSuchMethod(
            Invocation.getter(#noResponsibilityUserContent),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#noResponsibilityUserContent),
            ),
          )
          as String);

  @override
  String get noGuaranteeAccuracy =>
      (super.noSuchMethod(
            Invocation.getter(#noGuaranteeAccuracy),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#noGuaranteeAccuracy),
            ),
          )
          as String);

  @override
  String get noResponsibilityIndirectDamages =>
      (super.noSuchMethod(
            Invocation.getter(#noResponsibilityIndirectDamages),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#noResponsibilityIndirectDamages),
            ),
          )
          as String);

  @override
  String get disputeResolution =>
      (super.noSuchMethod(
            Invocation.getter(#disputeResolution),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#disputeResolution),
            ),
          )
          as String);

  @override
  String get negotiation =>
      (super.noSuchMethod(
            Invocation.getter(#negotiation),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#negotiation),
            ),
          )
          as String);

  @override
  String get resolveThroughNegotiation =>
      (super.noSuchMethod(
            Invocation.getter(#resolveThroughNegotiation),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#resolveThroughNegotiation),
            ),
          )
          as String);

  @override
  String get applicableLaw =>
      (super.noSuchMethod(
            Invocation.getter(#applicableLaw),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#applicableLaw),
            ),
          )
          as String);

  @override
  String get termsGovernedByLaw =>
      (super.noSuchMethod(
            Invocation.getter(#termsGovernedByLaw),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#termsGovernedByLaw),
            ),
          )
          as String);

  @override
  String get courtJurisdiction =>
      (super.noSuchMethod(
            Invocation.getter(#courtJurisdiction),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#courtJurisdiction),
            ),
          )
          as String);

  @override
  String get competentCourtsResolve =>
      (super.noSuchMethod(
            Invocation.getter(#competentCourtsResolve),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#competentCourtsResolve),
            ),
          )
          as String);

  @override
  String get termsUpdates =>
      (super.noSuchMethod(
            Invocation.getter(#termsUpdates),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#termsUpdates),
            ),
          )
          as String);

  @override
  String get rightToModify =>
      (super.noSuchMethod(
            Invocation.getter(#rightToModify),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#rightToModify),
            ),
          )
          as String);

  @override
  String get updateTerms =>
      (super.noSuchMethod(
            Invocation.getter(#updateTerms),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#updateTerms),
            ),
          )
          as String);

  @override
  String get notificationsSent =>
      (super.noSuchMethod(
            Invocation.getter(#notificationsSent),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#notificationsSent),
            ),
          )
          as String);

  @override
  String get acceptingChanges =>
      (super.noSuchMethod(
            Invocation.getter(#acceptingChanges),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#acceptingChanges),
            ),
          )
          as String);

  @override
  String get continuedUseMeansAgreement =>
      (super.noSuchMethod(
            Invocation.getter(#continuedUseMeansAgreement),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#continuedUseMeansAgreement),
            ),
          )
          as String);

  @override
  String get disagreeStopUse =>
      (super.noSuchMethod(
            Invocation.getter(#disagreeStopUse),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#disagreeStopUse),
            ),
          )
          as String);

  @override
  String get contactInformation =>
      (super.noSuchMethod(
            Invocation.getter(#contactInformation),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#contactInformation),
            ),
          )
          as String);

  @override
  String get questionsContact =>
      (super.noSuchMethod(
            Invocation.getter(#questionsContact),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#questionsContact),
            ),
          )
          as String);

  @override
  String get dIVIDEXTeam =>
      (super.noSuchMethod(
            Invocation.getter(#dIVIDEXTeam),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#dIVIDEXTeam),
            ),
          )
          as String);

  @override
  String get otherTerms =>
      (super.noSuchMethod(
            Invocation.getter(#otherTerms),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#otherTerms),
            ),
          )
          as String);

  @override
  String get severability =>
      (super.noSuchMethod(
            Invocation.getter(#severability),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#severability),
            ),
          )
          as String);

  @override
  String get invalidTerm =>
      (super.noSuchMethod(
            Invocation.getter(#invalidTerm),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#invalidTerm),
            ),
          )
          as String);

  @override
  String get entireAgreement =>
      (super.noSuchMethod(
            Invocation.getter(#entireAgreement),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#entireAgreement),
            ),
          )
          as String);

  @override
  String get entireAgreementText =>
      (super.noSuchMethod(
            Invocation.getter(#entireAgreementText),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#entireAgreementText),
            ),
          )
          as String);

  @override
  String get thankYouMessage =>
      (super.noSuchMethod(
            Invocation.getter(#thankYouMessage),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#thankYouMessage),
            ),
          )
          as String);

  @override
  String get acceptancePrompt =>
      (super.noSuchMethod(
            Invocation.getter(#acceptancePrompt),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#acceptancePrompt),
            ),
          )
          as String);

  @override
  String get termsOfServiceLink =>
      (super.noSuchMethod(
            Invocation.getter(#termsOfServiceLink),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#termsOfServiceLink),
            ),
          )
          as String);

  @override
  String get andConjunction =>
      (super.noSuchMethod(
            Invocation.getter(#andConjunction),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#andConjunction),
            ),
          )
          as String);

  @override
  String get privacyPolicyLink =>
      (super.noSuchMethod(
            Invocation.getter(#privacyPolicyLink),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#privacyPolicyLink),
            ),
          )
          as String);

  @override
  String get splashPage2Subtitle =>
      (super.noSuchMethod(
            Invocation.getter(#splashPage2Subtitle),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#splashPage2Subtitle),
            ),
          )
          as String);

  @override
  String get createAccountPrompt =>
      (super.noSuchMethod(
            Invocation.getter(#createAccountPrompt),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#createAccountPrompt),
            ),
          )
          as String);

  @override
  String get welcomeNewMessage =>
      (super.noSuchMethod(
            Invocation.getter(#welcomeNewMessage),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#welcomeNewMessage),
            ),
          )
          as String);

  @override
  String get createNewAccountPrompt =>
      (super.noSuchMethod(
            Invocation.getter(#createNewAccountPrompt),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#createNewAccountPrompt),
            ),
          )
          as String);

  @override
  String get welcomeBackMessage =>
      (super.noSuchMethod(
            Invocation.getter(#welcomeBackMessage),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#welcomeBackMessage),
            ),
          )
          as String);

  @override
  String get signInAccountPrompt =>
      (super.noSuchMethod(
            Invocation.getter(#signInAccountPrompt),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#signInAccountPrompt),
            ),
          )
          as String);

  @override
  String get emailVerificationMessage =>
      (super.noSuchMethod(
            Invocation.getter(#emailVerificationMessage),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#emailVerificationMessage),
            ),
          )
          as String);

  @override
  String get send =>
      (super.noSuchMethod(
            Invocation.getter(#send),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#send)),
          )
          as String);

  @override
  String get numberInputError1 =>
      (super.noSuchMethod(
            Invocation.getter(#numberInputError1),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#numberInputError1),
            ),
          )
          as String);

  @override
  String get numberInputError2 =>
      (super.noSuchMethod(
            Invocation.getter(#numberInputError2),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#numberInputError2),
            ),
          )
          as String);

  @override
  String get otpInputError2 =>
      (super.noSuchMethod(
            Invocation.getter(#otpInputError2),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#otpInputError2),
            ),
          )
          as String);

  @override
  String get otpLabel =>
      (super.noSuchMethod(
            Invocation.getter(#otpLabel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#otpLabel),
            ),
          )
          as String);

  @override
  String get emailVerificationCodeSent =>
      (super.noSuchMethod(
            Invocation.getter(#emailVerificationCodeSent),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#emailVerificationCodeSent),
            ),
          )
          as String);

  @override
  String get codeExpirationNotice =>
      (super.noSuchMethod(
            Invocation.getter(#codeExpirationNotice),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#codeExpirationNotice),
            ),
          )
          as String);

  @override
  String get otpInputPageChangeEmail =>
      (super.noSuchMethod(
            Invocation.getter(#otpInputPageChangeEmail),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#otpInputPageChangeEmail),
            ),
          )
          as String);

  @override
  String get emailOrPasswordIncorrect =>
      (super.noSuchMethod(
            Invocation.getter(#emailOrPasswordIncorrect),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#emailOrPasswordIncorrect),
            ),
          )
          as String);

  @override
  String get passwordIncorrect =>
      (super.noSuchMethod(
            Invocation.getter(#passwordIncorrect),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#passwordIncorrect),
            ),
          )
          as String);

  @override
  String get invalidOrExpiredOtp =>
      (super.noSuchMethod(
            Invocation.getter(#invalidOrExpiredOtp),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#invalidOrExpiredOtp),
            ),
          )
          as String);

  @override
  String get account =>
      (super.noSuchMethod(
            Invocation.getter(#account),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#account),
            ),
          )
          as String);

  @override
  String get transfer =>
      (super.noSuchMethod(
            Invocation.getter(#transfer),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#transfer),
            ),
          )
          as String);

  @override
  String get withdraw =>
      (super.noSuchMethod(
            Invocation.getter(#withdraw),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#withdraw),
            ),
          )
          as String);

  @override
  String get transactionReport =>
      (super.noSuchMethod(
            Invocation.getter(#transactionReport),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#transactionReport),
            ),
          )
          as String);

  @override
  String version(Object? versionNumber) =>
      (super.noSuchMethod(
            Invocation.method(#version, [versionNumber]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#version, [versionNumber]),
            ),
          )
          as String);

  @override
  String effectiveDate(Object? date) =>
      (super.noSuchMethod(
            Invocation.method(#effectiveDate, [date]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#effectiveDate, [date]),
            ),
          )
          as String);

  @override
  String email(Object? emailAddress) =>
      (super.noSuchMethod(
            Invocation.method(#email, [emailAddress]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#email, [emailAddress]),
            ),
          )
          as String);

  @override
  String address(Object? streetAddress) =>
      (super.noSuchMethod(
            Invocation.method(#address, [streetAddress]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#address, [streetAddress]),
            ),
          )
          as String);

  @override
  String phone(Object? phoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#phone, [phoneNumber]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#phone, [phoneNumber]),
            ),
          )
          as String);

  @override
  String lastUpdated(Object? date) =>
      (super.noSuchMethod(
            Invocation.method(#lastUpdated, [date]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#lastUpdated, [date]),
            ),
          )
          as String);

  @override
  String welcomeUser(Object? userName) =>
      (super.noSuchMethod(
            Invocation.method(#welcomeUser, [userName]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#welcomeUser, [userName]),
            ),
          )
          as String);
}
