// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtfEHaq1xdVC1IFK_s089ZIScd5NnTL0A',
    appId: '1:200103235347:web:3537fbfd2b8cd74a8554e6',
    messagingSenderId: '200103235347',
    projectId: 'dividex-4591f',
    authDomain: 'dividex-4591f.firebaseapp.com',
    storageBucket: 'dividex-4591f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVzt_6TYFTsVsoDCy1UouNnxkS4DDI2OY',
    appId: '1:200103235347:android:2ee7dac72ddc87d98554e6',
    messagingSenderId: '200103235347',
    projectId: 'dividex-4591f',
    storageBucket: 'dividex-4591f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHBbkc0B_EsJ8PHdqEDtEPDx_8dYmYVFA',
    appId: '1:200103235347:ios:e6f5af20fbbee9d18554e6',
    messagingSenderId: '200103235347',
    projectId: 'dividex-4591f',
    storageBucket: 'dividex-4591f.firebasestorage.app',
    iosBundleId: 'com.example.dividexDacn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHBbkc0B_EsJ8PHdqEDtEPDx_8dYmYVFA',
    appId: '1:200103235347:ios:e6f5af20fbbee9d18554e6',
    messagingSenderId: '200103235347',
    projectId: 'dividex-4591f',
    storageBucket: 'dividex-4591f.firebasestorage.app',
    iosBundleId: 'com.example.dividexDacn',
  );
}
