enum CurrencyEnum {
  vnd("VND", "Vietnamese đồng"),
  aed("AED", "United Arab Emirates dirham"),
  afn("AFN", "Afghan afghani"),
  all("ALL", "Albanian lek"),
  amd("AMD", "Armenian dram"),
  ang("ANG", "Netherlands Antillean guilder"),
  aoa("AOA", "Angolan kwanza"),
  ars("ARS", "Argentine peso"),
  aud("AUD", "Australian dollar"),
  awg("AWG", "Aruban florin"),
  azn("AZN", "Azerbaijani manat"),
  bam("BAM", "Bosnia and Herzegovina convertible mark"),
  bbd("BBD", "Barbados dollar"),
  bdt("BDT", "Bangladeshi taka"),
  bgn("BGN", "Bulgarian lev"),
  bhd("BHD", "Bahraini dinar"),
  bif("BIF", "Burundian franc"),
  bmd("BMD", "Bermudian dollar"),
  bnd("BND", "Brunei dollar"),
  bob("BOB", "Boliviano"),
  brl("BRL", "Brazilian real"),
  bsd("BSD", "Bahamian dollar"),
  btn("BTN", "Bhutanese ngultrum"),
  bwp("BWP", "Botswana pula"),
  byn("BYN", "Belarusian ruble"),
  bzd("BZD", "Belize dollar"),
  cad("CAD", "Canadian dollar"),
  cdf("CDF", "Congolese franc"),
  chf("CHF", "Swiss franc"),
  clp("CLP", "Chilean peso"),
  cny("CNY", "Chinese yuan"),
  cop("COP", "Colombian peso"),
  crc("CRC", "Costa Rican colón"),
  cup("CUP", "Cuban peso"),
  cve("CVE", "Cape Verdean escudo"),
  czk("CZK", "Czech koruna"),
  djf("DJF", "Djiboutian franc"),
  dkk("DKK", "Danish krone"),
  dop("DOP", "Dominican peso"),
  dzd("DZD", "Algerian dinar"),
  egp("EGP", "Egyptian pound"),
  ern("ERN", "Eritrean nakfa"),
  etb("ETB", "Ethiopian birr"),
  eur("EUR", "Euro"),
  fjd("FJD", "Fijian dollar"),
  fkp("FKP", "Falkland Islands pound"),
  fok("FOK", "Faroese króna"),
  gbp("GBP", "Pound sterling"),
  gel("GEL", "Georgian lari"),
  ggp("GGP", "Guernsey pound"),
  ghs("GHS", "Ghanaian cedi"),
  gip("GIP", "Gibraltar pound"),
  gmd("GMD", "Gambian dalasi"),
  gnf("GNF", "Guinean franc"),
  gtq("GTQ", "Guatemalan quetzal"),
  gyd("GYD", "Guyanese dollar"),
  hkd("HKD", "Hong Kong dollar"),
  hnl("HNL", "Honduran lempira"),
  hrk("HRK", "Croatian kuna"),
  htg("HTG", "Haitian gourde"),
  huf("HUF", "Hungarian forint"),
  idr("IDR", "Indonesian rupiah"),
  ils("ILS", "Israeli new shekel"),
  imp("IMP", "Manx pound"),
  inr("INR", "Indian rupee"),
  iqd("IQD", "Iraqi dinar"),
  irr("IRR", "Iranian rial"),
  isk("ISK", "Icelandic króna"),
  jep("JEP", "Jersey pound"),
  jmd("JMD", "Jamaican dollar"),
  jod("JOD", "Jordanian dinar"),
  jpy("JPY", "Japanese yen"),
  kes("KES", "Kenyan shilling"),
  kgs("KGS", "Kyrgyzstani som"),
  khr("KHR", "Cambodian riel"),
  kid("KID", "Kiribati dollar"),
  kmf("KMF", "Comorian franc"),
  krw("KRW", "South Korean won"),
  kwd("KWD", "Kuwaiti dinar"),
  kyd("KYD", "Cayman Islands dollar"),
  kzt("KZT", "Kazakhstani tenge"),
  lak("LAK", "Lao kip"),
  lbp("LBP", "Lebanese pound"),
  lkr("LKR", "Sri Lankan rupee"),
  lrd("LRD", "Liberian dollar"),
  lsl("LSL", "Lesotho loti"),
  lyd("LYD", "Libyan dinar"),
  mad("MAD", "Moroccan dirham"),
  mdl("MDL", "Moldovan leu"),
  mga("MGA", "Malagasy ariary"),
  mkd("MKD", "Macedonian denar"),
  mmk("MMK", "Burmese kyat"),
  mnt("MNT", "Mongolian tögrög"),
  mop("MOP", "Macanese pataca"),
  mru("MRU", "Mauritanian ouguiya"),
  mur("MUR", "Mauritian rupee"),
  mvr("MVR", "Maldivian rufiyaa"),
  mwk("MWK", "Malawian kwacha"),
  mxn("MXN", "Mexican peso"),
  myr("MYR", "Malaysian ringgit"),
  mzn("MZN", "Mozambican metical"),
  nad("NAD", "Namibian dollar"),
  ngn("NGN", "Nigerian naira"),
  nio("NIO", "Nicaraguan córdoba"),
  nok("NOK", "Norwegian krone"),
  npr("NPR", "Nepalese rupee"),
  nzd("NZD", "New Zealand dollar"),
  omr("OMR", "Omani rial"),
  pab("PAB", "Panamanian balboa"),
  pen("PEN", "Peruvian sol"),
  pgk("PGK", "Papua New Guinean kina"),
  php("PHP", "Philippine peso"),
  pkr("PKR", "Pakistani rupee"),
  pln("PLN", "Polish złoty"),
  pyg("PYG", "Paraguayan guaraní"),
  qar("QAR", "Qatari riyal"),
  ron("RON", "Romanian leu"),
  rsd("RSD", "Serbian dinar"),
  rub("RUB", "Russian ruble"),
  rwf("RWF", "Rwandan franc"),
  sar("SAR", "Saudi riyal"),
  sbd("SBD", "Solomon Islands dollar"),
  scr("SCR", "Seychellois rupee"),
  sdg("SDG", "Sudanese pound"),
  sek("SEK", "Swedish krona"),
  sgd("SGD", "Singapore dollar"),
  shp("SHP", "Saint Helena pound"),
  sle("SLE", "Sierra Leonean leone"),
  sos("SOS", "Somali shilling"),
  srd("SRD", "Surinamese dollar"),
  ssp("SSP", "South Sudanese pound"),
  stn("STN", "São Tomé and Príncipe dobra"),
  syp("SYP", "Syrian pound"),
  szl("SZL", "Swazi lilangeni"),
  thb("THB", "Thai baht"),
  tjs("TJS", "Tajikistani somoni"),
  tmt("TMT", "Turkmenistan manat"),
  tnd("TND", "Tunisian dinar"),
  top("TOP", "Tongan paʻanga"),
  try_("TRY", "Turkish lira"),
  ttd("TTD", "Trinidad and Tobago dollar"),
  tvd("TVD", "Tuvaluan dollar"),
  twd("TWD", "New Taiwan dollar"),
  tzs("TZS", "Tanzanian shilling"),
  uah("UAH", "Ukrainian hryvnia"),
  ugx("UGX", "Ugandan shilling"),
  usd("USD", "United States dollar"),
  uyu("UYU", "Uruguayan peso"),
  uzs("UZS", "Uzbekistani som"),
  ves("VES", "Venezuelan bolívar"),
  vuv("VUV", "Vanuatu vatu"),
  wst("WST", "Samoan tālā"),
  xaf("XAF", "Central African CFA franc"),
  xcd("XCD", "East Caribbean dollar"),
  xdr("XDR", "Special drawing rights"),
  xof("XOF", "West African CFA franc"),
  xpf("XPF", "CFP franc"),
  yer("YER", "Yemeni rial"),
  zar("ZAR", "South African rand"),
  zmw("ZMW", "Zambian kwacha"),
  zwl("ZWL", "Zimbabwean dollar");

  final String code;
  final String description;

  const CurrencyEnum(this.code, this.description);
}

List<CurrencyEnum> getAllCurrencies() {
  return CurrencyEnum.values;
}

enum SplitTypeEnum {
  equal("equal", "Equal split"),
  percentage("percentage", "Percentage split"),
  custom("custom", "Custom split");

  final String code;
  final String description;

  const SplitTypeEnum(this.code, this.description);
}

enum StatusEnum {
  active("active", "Active"),
  deleted("deleted", "Deleted");

  final String code;
  final String description;

  const StatusEnum(this.code, this.description);
}
