// Mocks generated by Mockito 5.4.6 from annotations
// in Dividex/test/auth/presentation/bloc/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:Dividex/features/auth/data/models/token_respond_model.dart'
    as _i3;
import 'package:Dividex/features/auth/domain/auth_repository.dart' as _i2;
import 'package:Dividex/features/auth/domain/usecase.dart' as _i4;
import 'package:Dividex/features/user/data/models/user_model.dart' as _i6;
import 'package:Dividex/shared/services/local/hive_service.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthRepository_0 extends _i1.SmartFake
    implements _i2.AuthRepository {
  _FakeAuthRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResponseModel_1 extends _i1.SmartFake
    implements _i3.AuthResponseModel {
  _FakeAuthResponseModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RegisterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUseCase extends _i1.Mock implements _i4.RegisterUseCase {
  MockRegisterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i5.Future<_i3.AuthResponseModel> call(
    _i6.UserModel? user,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [user, password]),
            returnValue: _i5.Future<_i3.AuthResponseModel>.value(
              _FakeAuthResponseModel_1(
                this,
                Invocation.method(#call, [user, password]),
              ),
            ),
          )
          as _i5.Future<_i3.AuthResponseModel>);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i4.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i5.Future<_i3.AuthResponseModel> call(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#call, [email, password]),
            returnValue: _i5.Future<_i3.AuthResponseModel>.value(
              _FakeAuthResponseModel_1(
                this,
                Invocation.method(#call, [email, password]),
              ),
            ),
          )
          as _i5.Future<_i3.AuthResponseModel>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i4.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i5.Future<void> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [EmailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmailUseCase extends _i1.Mock implements _i4.EmailUseCase {
  MockEmailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i5.Future<void> requestEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#requestEmail, [email]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> checkEmailExists(String? email, String? otp) =>
      (super.noSuchMethod(
            Invocation.method(#checkEmailExists, [email, otp]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#checkEmailExists, [email, otp]),
              ),
            ),
          )
          as _i5.Future<String>);
}

/// A class which mocks [ResetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordUseCase extends _i1.Mock
    implements _i4.ResetPasswordUseCase {
  MockResetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i5.Future<void> resetPassword(String? newPassword, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [newPassword, token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> changePassword(String? newPassword, String? oldPassword) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [newPassword, oldPassword]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateFcmToken(String? fcmToken) =>
      (super.noSuchMethod(
            Invocation.method(#updateFcmToken, [fcmToken]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [HiveService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveService extends _i1.Mock implements _i8.HiveService {
  MockHiveService() {
    _i1.throwOnMissingStub(this);
  }
}
